{% set version = "3.1.0" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-processx
  version: {{ version|replace("-", "_") }}

source:
  fn: processx_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/processx_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/processx/processx_{{ version }}.tar.gz
  sha256: 11ac120ab4e4aa0e99c9b2eda87d07bc683bab735f1761e95e5ddacd311b5972

build:
  number: 0
  script: R CMD INSTALL --build .
  skip: True  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-r6
    - r-assertthat
    - r-crayon
    - r-debugme
    - posix  # [win]
    - {{native}}toolchain  # [win]
    - gcc  # [not win]
  run:
    - r-base
    - r-r6
    - r-assertthat
    - r-crayon
    - r-debugme
    - libgcc  # [not win]

test:
  commands:
    - $R -e "library('processx')"  # [not win]
    - "\"%R%\" -e \"library('processx')\""  # [win]

about:
  home: https
  license: MIT
  license_file: LICENSE
  summary: Portable tools to run system processes in the background. It can check if a background
    process is running; wait on a background process to finish; get the exit status
    of finished processes; kill background processes and their children; restart processes.
    It can read the standard output and error of the processes, using non-blocking connections.
    'processx' can poll a process for standard output or error, with a timeout. It can
    also poll several processes at once.

extra:
  recipe-maintainers:
    - ocefpaf
