travis:
  secure:
    BINSTAR_TOKEN: vfd+zUlSG2dIaEiq/tass7oiPZfWGnkhA3Al3oOqEpbEB3NsnS6sWi/LL/taEBEP92QxmKC0qz8r61ij9XiSsRpBE53u9H27Q+0dkhY+/qwxqnBf1yISY2JEdKJtCg82jtgIfJPFjJutXv+T/oHZ9r1LSWUaamZj2ynnoHzkN5DANSDFkbEUTJPIFFFPpcBt3mnPk6SU6mRgIjXA5u/VURUuZgFCzqm0lBoUhBEycPU3Mzsx6oQmDexhZEKmCCEGixVxTyIH+p6pa8FaceLJxwKwDQajW2cMbvBJdZeG1KG3O1UIP8Rr3gJxYvLfrevF9aRQEdW0nUXWaY4qOxv8sTs2q9hqbG0f0Wmj3+CrmD+k9zvKmT5H8e3HtfLhLQoWjF3hVk8tfrUW7+mTZXUTNRQnH0mVBgt8al1PBz00qIJCYrdE0JyH3WyrzUQokFEat5yX+K4kArQCBcG5RUYdVjkoRVuKovtO75vDy/RckhhClqJIfxZBYOz1Sh/ax5FmVrdfFHLO1L9b88uUisyf4VePjfUj86IkJxskS4e7L5Fjlp6JKzLDEy1Bha29FFwfZWDBwGVf1R9U0+3zr6i0m5M6gNmzkLSVtthRy4jJxl4TOiFVsjytTEpGeOtNPbYHVevtU0sdx4Cneowg6zSERIgvJN1Ad7ngFE+88Xgm3gI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
